version: "3.9"

services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - app.env
    container_name: db

  ranks:
    build: .
    platform: linux/amd64
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ranks
    ports:
      - "8000:8000"
    env_file:
      - app.env
    depends_on:
      - db

volumes:
  pg:
   driver: local
