version: "3.9"

services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - app.env
    container_name: db

  ranks:
    build: ./
    platform: linux/amd64
    command: sh entry.sh
    volumes:
      - .:/ranks
      - static:/ranks/static
      - nginx_conf:/ranks/nginx/
    expose:
      - 8000
    env_file:
      - app.env
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/ranks/static
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - 1377:80
    depends_on:
      - ranks
    restart: always

volumes:
  pg:
   driver: local
  static:
  nginx_conf:
