# Generated by Django 4.0.4 on 2022-05-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование купона')),
                ('discount_id', models.CharField(max_length=255, verbose_name='ID купона')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('price_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Цены')),
                ('currency', models.CharField(choices=[('USD', 'Доллар'), ('RUB', 'Рубль')], max_length=255, verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sales tax', 'Налог с продажи'), ('VAT', 'НДС')], max_length=255, verbose_name='Тип налога')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание налога')),
                ('tax_rate_id', models.CharField(max_length=255, verbose_name='ID налога')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.discount', verbose_name='Скидка')),
                ('items', models.ManyToManyField(to='payment.item', verbose_name='Товары')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.tax', verbose_name='Налог')),
            ],
        ),
    ]
